### ISSUE TITLE
Use stahnma/puppetlabs_yum and ploperations/puppetlabs_apt to handle Puppet repositories

### ISSUE THREAD

**Issue by juniorsysadmin** [voxpupuli/puppet-puppetserver#37]
Ideally this module should use stahnma/puppetlabs_yum and ploperations/puppetlabs_apt

**Comment by juniorsysadmin** [comment]
https://github.com/puppetlabs-operations/puppet-puppetlabs_apt/pull/14

**Comment by vinzent** [comment]
as commented in https://github.com/voxpupuli/puppet-puppetserver/pull/20#issuecomment-277067206 the module should maybe better not provide the repo class as the person installing puppetserver with puppet very likely already has the puppetlabs repo configured or manages packages with internal repositories.

The README.md should point to the modules providing smooth repo integration for other users to be included in profiles.

**Comment by juniorsysadmin** [comment]
```$repo_class```

**Comment by vinzent** [comment]
@juniorsysadmin repo_class ? do you mean passing repo_class to puppetserver::repository?

```
# example class
class puppetserver::repository( $repo_class = $puppetserver::params::repo_class )  { 
  include $repo_class
}

# profile
class { puppetserver::repository: repo_class => `::puppetlabs_yum` }
class { puppetserver: }

## versus

# profile
include ::puppetlabs_yum
include ::puppetserver

Class['puppetlabs_yum'] -> Class['puppetserver']
```


IMHO: 

* puppet-puppetserver shouldn't provide the repoository config because it changes and others provide modules to provide exactly this service
* puppet-puppetserver shouldn't depend on the modules because when installing puppet-agent most people already have the repo configured and to install puppetserver with puppet one requires to install puppet before. 
* puppet-puppetserver shouldn't care about puppet3 anymore because we ware puppet 4 only we don't support puppet3 anymore. (https://voxpupuli.org/blog/2016/12/22/putting-down-puppet-3/)
* puppet-puppetserver shouldn't depend on the modules because if installing puppetserver with puppet and I have only internal repositories I don't wan't  to include puppet modules in my env which I will never use.
* puppet-puppetserver should provide documentation howto configure puppet repo with 3rd party modules

**Comment by juniorsysadmin** [comment]
@vinzent Actually that's better. Can't remember the reason for filing this issue other than removing the repository class code.
